SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PG_IN_OBTENER_FOLIO_POR_EMISOR]
(
	@PP_RAZON_SOCIAL [int]	
)
AS
BEGIN
	DECLARE @VP_FOLIO [int] = 0

	-- Verificar que la razon social tenga folios disponibles
	DECLARE @VP_FOLIOS_DISPONIBLES [int] = 0
	SELECT @VP_FOLIOS_DISPONIBLES = FOLIOS FROM FOLIOS_DISPONIBLES

	IF @VP_FOLIOS_DISPONIBLES > 0
	BEGIN
		-- Obtener el ultimo folio para la razon social
		SELECT @VP_FOLIO = MAX(ID_FACTURA) FROM FACTURAS
		WHERE K_RAZON_SOCIAL = @PP_RAZON_SOCIAL
		-- Decrementar la cantidad de folios disponibles
		UPDATE FOLIOS_DISPONIBLES
			SET FOLIOS = FOLIOS - 1
		WHERE K_RAZON_SOCIAL = @PP_RAZON_SOCIAL
	END 	
	
	RETURN @VP_FOLIO
END
GO